name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 📦 Install dependencies
      run: npm ci
      env:
        CI: true

    - name: 🧪 Run tests
      run: |
        npm run doctest || true # TODO: Add all doctests
        npm test
      env:
        CI: true

    - name: 💄 Code style
      run: npm run style
      env:
        CI: true
