name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install doctest standard --save-dev
        pwd
        ls -la
        echo "A"
        node_modules/doctest Sorts/BogoSort.js || true
        echo "B"
        npx doctest Sorts/BogoSort.js || true
        echo "C"
        node -e "node_modules/doctest('Sorts/BogoSort.js', {})" || true
        echo "D"
        # npm install standard --save-dev
        npx standard
        cd Linear-Algebra-Javascript
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
