# This GitHub Action updates the DIRECTORY.md file (if needed) when doing a git push
name: Update Directory

on:
  push:
    branches-ignore:
      "master"

jobs:
  updateDirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🗄️ Create Directory from JS files
        run: node .github/workflows/UpdateDirectory.mjs

      - name: Configure Github Action
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'

      - name: 🤓 Commit & push new Directory (if needed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git commit -am "Updated Documentation in README.md"
            git push
          else
            echo "NO CHANGES DETECTED"
          fi
